### ISSUE TITLE
Add links to the hexlet to all videos

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#12]

**Comment by Glebuar** [comment]
Для этого мне нужен доступ к аккаунту на ютубе или твоё предложение как это сделать :)

**Comment by Glebuar** [comment]
How I can get access to your youtube account?

**Comment by b0noI** [comment]
this is my task, I will do it

**Comment by Glebuar** [comment]
Don't forget replace the video on corrected

**Comment by b0noI** [comment]
done
