### ISSUE TITLE
Review first lesson

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#13]
This task includes:
- watch less m0e0;
- answer to all students questions;
- fix video if needed;
- re-factor questions;

**Comment by Glebuar** [comment]
What means m0e0?

**Comment by Glebuar** [comment]
Where I should answer students questions and how to know answers?

**Comment by b0noI** [comment]
@Glebuar 
> What means m0e0?
m0e0 == module 0 episode 0

> Where I should answer students questions and how to know answers?
link to the lesson: https://hexlet.io/lessons/intro_to_java

this lesson should be in "done. done. done" state after this task is finished

**Comment by Glebuar** [comment]
Вопрос:
"для тестирования нужны какие то особые знания, или те что вы даете в своих лекциях вполне подойдут и при устройстве на работу будут играть ключевую роль? Какой багаж знаний нужен для QA? "
Вариант ответа: 
В лекциях даются базовые теоретические и практические знания, которые помогут Вам начать получать тот опыт, который требуется при устройстве на  работу, а так же пройти сертификацию Oracle, что будет плюсом на собеседовании. Требуемый багаж знаний зависит от конкретной вакансии, на которую вы претендуете. Одни компании готовы обучать человека без опыта, другие предъявляют повышенные требования к претендентам.
