### ISSUE TITLE
Wire down a request about landing page on Hexlet

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#15]

**Comment by Glebuar** [comment]
Where I should write it? Why am I writing English? :)

**Comment by b0noI** [comment]
FaceBook, or here and then we will extend it to the FB

**Comment by Glebuar** [comment]
https://drive.google.com/open?id=1IpRkyaugboWpduLTRnyMa_V4-TSyEF2dRQ-1xA8fxHU&authuser=0
