### ISSUE TITLE
fix practice of the lessons

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#20]
task:
- practice should be attached to correct lessons
- each practice should be renamed according to the lesson name (practice name == lesson name)

**Comment by Glebuar** [comment]
Как определить правильную принадлежность практики уроку?

**Comment by b0noI** [comment]
@Glebuar только путем прослушивания урока и сравнивая практику

**Comment by Glebuar** [comment]
Разобрался с практикой. Ситуация такая - всё правильно прикреплено, но есть уроки где практика прикреплена от другого урока, а своей у него нет. При чём удалить или выбрать пустое значение нельзя, можно выбрать только другую практику. Поэтому ошибка пока остаётся. Надо или создать практику для урока с ошибочной либо просить их удалить.

- Пакеты в Java (нет практики, прилеплена чужая)
- Методы классов (нет практики, прилеплена чужая)

Надо исправить как можно скорее, будут жаловаться в комментах, а мы их удалять не можем

**Comment by b0noI** [comment]
напиши на FB они быстро пофиксят, так как сейчас все спят =( прийдется завтра всеравно ждать но если кинуть запрос сейчас то завтра там первым делом зафиксят. Только запрос должен включать все детали достаточные что бы они руками поправили
