### ISSUE TITLE
Create RAW Mind podcast

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#21]
sub-task:
- find platform that supports RSS feeds like rPod (podFm?);
- merge 2 tracks and create audio file;
- upload audio file to the podcast terminal;
- create simple podcast title img;
- upload podcast to the iTines;

**Comment by Glebuar** [comment]
1. Выложи свою дорожку в папку Подкасты --> Первый
2. Напиши свои рекомендации для повышения качества при сведении дорог

**Comment by b0noI** [comment]
@Glebuar аудио залито, по поводу того как обрабатывать:
- добавляешь обе дорожки ы один проект Audacity
- синхронизируешь звук
- обрабатываешь фильтром Нормализатор - этот фильтр должен уровнять громкости обоих каналов так как практически никогда запись с двух микроволновой не бывает на идеально одинаковом уровне что жутко раздражает при прослушивании без этого фильтра
- обрабатываешь Компрессором (поставь галочку "на основе пиков") - этот фильтр уберет большие пики на дорожке так как после нормализатор большие выпады могут стать еще больше иногда это случается если кто-то случайно или эмоционально в какой-то момент повысил голос
- если нужно то еще обработать подателем шумом - этот фильтр нужно включать только при действительной надобности, он банально убьет уровень громкости и частично сведет на нет результат прошлых фильтров, посему очень важно глянуть на звук до и после. Я почти никогда не пользуюсь шумо-подавлением (как минимум тем что идет в Audacity)
- если где найдешь бесплатную хорошую фоновую музыку то можешь добавить на фон, если нет то не страшно, первые N выпуском будем без нее

**Comment by Glebuar** [comment]
Последний пункт "upload podcast to the iTines" должен быть первым, т.к. оказалось, что у него определённые требования в предыдущим пунктам :)

**Comment by Glebuar** [comment]
На счёт шума - в Audacity фильтр называется Удаление шума - выделяешь часть где на фоне только шум, создаёшь модель шума и удаляешь его этим фильтром. Громкость остаётся та же, звук становится чистым. Помню какая-то была программа с походим механизмом, она удаляла шум так что искажалась часть голоса, а здесь нормально. Возможно дело в настройках. Вообщем можно пользоваться.
