### ISSUE TITLE
Quality improvements for the lesson #3

### ISSUE THREAD

**Issue by b0noI** [b0noI/TicTacToe#22]
same requirements as for lesson 1 and 2 (make it done/done/done)

**Comment by Glebuar** [comment]
1. Что делать с "советчиками" в комментариях, которые дают неимоверно полезные подсказки по материалу, как например, что язык питон тоже скриптовый, лучше бы назвать это метод вот так и т.д.? Оставлять без комментариев или что-то отписывать, что бы завязывалась дискуссия?

2. Если вопросы в уроке божественны и  прекрасны , что не хочется ничего удалять и добавлять? :)
