### ISSUE TITLE
Изменение на канале youtube

### ISSUE THREAD

**Issue by Glebuar** [b0noI/TicTacToe#26]
1. Переименовать ролики, относящиеся к курсу по Java, соответственно названиям в уроков (при просмотре через платформу хекслетио ролики подписываются названием с youtube, т.е. желательно что-бы названия совпадали, т.к. их тоже видят пользователи).

2. Для каждого урока на youtube подобрать ключевые слова, связав их в текст. Т.е. сделать хорошее описание для видео (можно взять за основу описание урока с платформы где оно есть).

3. Заменить ссылки на youtube после получения домена java.hexlet.io

**Comment by Glebuar** [comment]
Что-то не получилось обоих назначить на выполнение :)

**Comment by b0noI** [comment]
@Glebuar task should be split on the 2 tasks, should be only 1 owner, with 1+ owners task will be never done =)

**Comment by Glebuar** [comment]
4. Сделать брендирование Ютуб канала (например логотип, слоган, фотовое изображение)
